language: php

php: [5.3, 5.4, 5.5, 5.6, hhvm]

before_script:
    - gem install mailcatcher
    - mailcatcher
    - composer install --prefer-source --no-interaction --no-progress
    - export PATH=./vendor/bin:$PATH

script:
  - phpspec run -f pretty --no-interaction
  - behat --strict
